Repository NordicSemiconductor/pc-nrfconnect-board-configurator, pull requests merged in 2024-09, with the labels that each got.

#117 NCD-962: Indicate unwritten changes
  Changelog.md
  package-lock.json
  package.json
  src/SidePanel.tsx
  src/app/DirtyDot.tsx
  src/app/dirtydot.scss
  src/common/boards/BoardControllerConfigDefinition.ts
  src/features/ConfigDataPreview/ConfigDataPreview.tsx
  src/features/ConfigSlideSelector/ConfigSlideSelector.tsx
  src/features/ConfigSwitch/ConfigSwitch.tsx
  src/features/Configuration/boardControllerConfigSlice.ts
  src/features/Configuration/boardDefinitions.ts
  src/features/VCOMConfiguration/VCOMConfiguration.tsx
  src/features/VoltageConfiguration/VoltageConfiguration.tsx
Labels: doc required, ui required

#118 NCD-771: UX review of first version
  src/features/VoltageConfiguration/VoltageConfiguration.tsx
Labels: doc not required, ui required

#120 Prepare for release v0.3.4
  Changelog.md
Labels: doc not required, ui not required

#119 doc: unwritten changes + nRF54 support
  doc/docs/index.md
  doc/docs/overview.md
  doc/docs/revision_history.md
  doc/docs/screenshots/board_configurator_unwritten_config.png
  doc/docs/screenshots/board_configurator_unwritten_options.png
  doc/docs/updating.md
Labels: documentation, doc required

#125 Release 0 3 6
  Changelog.md
  package-lock.json
  package.json
Labels: doc not required, ui not required

#126 NCD-1044: Added nRF54 notes to main screen
  Changelog.md
  package-lock.json
  package.json
  src/features/Configuration/Configuration.tsx
Labels: doc required, ui required
