Repository NordicSemiconductor/pc-nrfconnect-board-configurator, pull requests merged in 2024-11, with the labels that each got.

#131 Update nrfutil to v2.7.3
  Changelog.md
  package-lock.json
  package.json
Labels: doc not required, ui not required

#132 Prepare for release v0.3.8
  Changelog.md
Labels: doc not required, ui not required

#134 Fix release v0.3.8 release date
  Changelog.md
Labels: doc not required, ui not required

#136 NCD-1094: Fix nRF54 L15 LED control wording
  Changelog.md
  package-lock.json
  package.json
  src/common/boards/nrf_PCA10156_0.3.0.json
Labels: doc not required, ui not required

#137 Prepare for release v0.3.9
  Changelog.md
Labels: doc not required, ui not required

#135 doc: remove nrf connect from app name in docs + edits
  README.md
  doc/docs/index.md
  doc/docs/installing.md
  doc/docs/overview.md
  doc/docs/troubleshooting.md
  doc/docs/updating.md
  doc/mkdocs.yml
  doc/zoomin/custom.properties
  src/features/Configuration/Configuration.tsx
  src/index.tsx
Labels: documentation, doc required

#138 doc: zoomin: add app to app name
  doc/zoomin/custom.properties
Labels: documentation, doc required

#141 NCD-1101: Update nrfutil-device dependency to v2.7.6
  Changelog.md
  package-lock.json
  package.json
Labels: doc not required, ui not required

#142 Prepare release of v.0.3.10
  Changelog.md
Labels: doc not required, ui not required

#143 .github: update zoomin.yml to use upload v4
  .github/workflows/zoomin.yml
Labels: documentation
