Repository NordicSemiconductor/pc-nrfconnect-board-configurator, pull requests merged in 2024-01, with the labels that each got.

#3 doc: add documentation for board configurator
  .github/workflows/zoomin-publish-dev.yml
  .github/workflows/zoomin-publish.yml
  .github/workflows/zoomin.yml
  doc/docs/index.md
  doc/docs/installing.md
  doc/docs/overview.md
  doc/docs/revision_history.md
  doc/docs/screenshots/board_configurator_connected.png
  doc/docs/screenshots/board_configurator_overview.png
  doc/docs/screenshots/board_ctrl_open_log.png
  doc/docs/troubleshooting.md
  doc/docs/updating.md
  doc/mkdocs.yml
  doc/zoomin/custom.properties
  doc/zoomin/tags.yml
Labels: documentation

#24 Add label check workflow
  .github/workflows/labels.yml
Labels: doc not required

#26 NCD-672: initial code review
  src/SidePanel.tsx
  src/app/DeviceSelector.tsx
  src/app/appReducer.ts
  src/common/boards/BoardControllerConfigDefinition.ts
  src/features/ConfigDataPreview/ConfigDataPreview.tsx
  src/features/ConfigDataPreview/configdatapreview.scss
  src/features/ConfigSlideSelector/ConfigSlideSelector.tsx
  src/features/ConfigSwitch/ConfigSwitch.tsx
  src/features/Configuration/Configuration.tsx
  src/features/Configuration/boardControllerConfigSlice.ts
  src/features/Configuration/configuration.scss
  src/features/Device/deviceSlice.ts
  src/features/Device/types.ts
  src/features/VCOMConfiguration/VCOMConfiguration.tsx
  src/features/VCOMConfiguration/types.ts
  src/features/VCOMConfiguration/vcomconfig.scss
  src/features/VoltageConfiguration/VoltageConfiguration.tsx
  src/index.scss
  src/index.tsx
Labels: doc not required

#30 Update to use pc-nrfconnect-shared v152.0.0
  package-lock.json
  package.json
  src/SidePanel.tsx
  src/app/DeviceSelector.tsx
Labels: doc not required

#29 NCD-660: Disable write button on click, enable on write finished
  src/SidePanel.tsx
Labels: doc required

#31 Version bump to release v0.1.2. Updated changelog
  Changelog.md
  package.json
Labels: doc not required

#33 Bump version to release v0.1.3. Updated Changelog
  Changelog.md
  package.json
Labels: doc not required
