Repository NordicSemiconductor/pc-nrfconnect-board-configurator, pull requests merged in 2024-03, with the labels that each got.

#60 doc: update for 0.1.8 release
  doc/docs/overview.md
  doc/docs/revision_history.md
  doc/docs/screenshots/board_configurator_connected.png
  doc/docs/screenshots/board_configurator_overview.png
Labels: documentation, doc required

#63 NCD-748: Name PMIC ports
  Changelog.md
  src/common/boards/nrf_PCA10153_0.10.0_9161.json
  src/common/boards/nrf_PCA10156_0.2.0.json
  src/common/boards/nrf_PCA10156_0.3.0.json
  src/common/boards/nrf_PCA10171_0.2.0_9151.json
Labels: doc not required, ui not required

#68 NCD-764: Fix maximum voltage for nRF54L15-DKs
  Changelog.md
  src/common/boards/nrf_PCA10156_0.2.0.json
  src/common/boards/nrf_PCA10156_0.3.0.json
Labels: doc not required, ui not required

#67 NCD-774: Support nRF54H20-DK r0.7.0
  Changelog.md
  src/common/boards/nrf_PCA10175_54H20_0.7.0.json
  src/features/Configuration/boardDefinitions.ts
Labels: doc required, ui not required

#70 Prepare for release of v0.1.9
  Changelog.md
  package.json
Labels: doc required, ui not required

#71 Don't depend on engine 4.4.1
  package.json
Labels: doc not required, ui not required

#72 Prepare for release of v0.1.10
  Changelog.md
  package.json
Labels: doc not required, ui not required

#73 NCD-776: Limit voltage presets to fit the boards range
  Changelog.md
  src/features/VoltageConfiguration/VoltageConfiguration.tsx
Labels: doc not required, ui not required

#75 doc: update for 0.1.9 release
  doc/docs/revision_history.md
  doc/docs/screenshots/board_configurator_connected.png
Labels: documentation, doc required

#74 NCD-787: Enable telemetry
  src/index.tsx
Labels: doc not required, ui not required

#76 Prepare for release of v0.1.11
  Changelog.md
  package.json
Labels: doc not required, ui not required

#77 NCD-768: Fix VCOM component UX
  src/features/VCOMConfiguration/VCOMConfiguration.tsx
Labels: doc required, ui required

#81 NCD-769: Update UI on VoltageConfiguration component
  src/features/VoltageConfiguration/VoltageConfiguration.tsx
Labels: doc not required, ui required

#82 NCD-773: Update UI, improve UX, rewrite board definition files
  src/common/boards/BoardControllerConfigDefinition.ts
  src/common/boards/nrf_PCA10145_54H20.json
  src/common/boards/nrf_PCA10153_0.10.0_9161.json
  src/common/boards/nrf_PCA10153_0.9.1_9161.json
  src/common/boards/nrf_PCA10156_0.2.0.json
  src/common/boards/nrf_PCA10156_0.3.0.json
  src/common/boards/nrf_PCA10171_0.2.0_9151.json
  src/common/boards/nrf_PCA10175_54H20_0.7.0.json
  src/features/ConfigSlideSelector/ConfigSlideSelector.tsx
  src/features/ConfigSwitch/ConfigSwitch.tsx
  src/features/Configuration/Configuration.tsx
  src/features/VCOMConfiguration/VCOMConfiguration.tsx
Labels: doc required, ui required

#83 Release v0.1.12
  Changelog.md
  package.json
  src/common/boards/nrf_PCA10156_0.2.0.json
Labels: doc not required, ui not required

#80 doc: v0.1.12 update
  Changelog.md
  doc/docs/revision_history.md
  doc/docs/screenshots/board_configurator_connected.png
  doc/docs/updating.md
Labels: documentation, doc required

#84 NCD-773: Fix style error from tailwind stanza order
  src/features/VoltageConfiguration/VoltageConfiguration.tsx
Labels: doc not required, ui not required

#85 NCD-822: Support nRF-9161-DK r1.0.0
  Changelog.md
  doc/docs/index.md
  src/common/boards/nrf_PCA10153_1.0.0_9161.json
  src/features/Configuration/boardDefinitions.ts
Labels: doc required, ui not required

#86 Chore: Rename boarddef files
  src/common/boards/nrf_PCA10145_0.8.0_54H20.json
  src/common/boards/nrf_PCA10175_0.7.0_54H20.json
  src/features/Configuration/boardDefinitions.ts
Labels: doc not required, ui not required

#87 Prepare for release of v0.1.13
  Changelog.md
  package.json
Labels: doc not required, ui not required

#88 NCD-822: Support PMIC on nRF9161-DK r1.0.0
  src/common/boards/nrf_PCA10153_1.0.0_9161.json
Labels: doc not required, ui not required

#89 Prepare for release of v0.2.0
  Changelog.md
  package.json
Labels: doc not required, ui not required

#90 doc: update for v0.20.0
  .github/workflows/zoomin-publish-dev.yml
  .github/workflows/zoomin-publish.yml
  doc/docs/revision_history.md
Labels: documentation, doc required
