Repository NordicSemiconductor/pc-nrfconnect-board-configurator, pull requests merged in 2024-02, with the labels that each got.

#36 NCD-343: Read configuration, merge with defaults, show in GUI
  Changelog.md
  package-lock.json
  package.json
  src/SidePanel.tsx
  src/app/DeviceSelector.tsx
  src/features/ConfigDataPreview/ConfigDataPreview.tsx
  src/features/ConfigSlideSelector/ConfigSlideSelector.tsx
  src/features/ConfigSwitch/ConfigSwitch.tsx
  src/features/Configuration/Configuration.tsx
  src/features/Configuration/boardControllerConfigSlice.ts
  src/features/Configuration/hardwareConfiguration.ts
Labels: doc required

#40 NCD-709: Reword IO expander card, change to slide switch
  Changelog.md
  src/common/boards/nrf_PCA10153_0.9.1_9161.json
Labels: doc required

#39 Bump version to release v0.1.4
  package.json
Labels: doc not required

#43 ci: use shared labels workflow
  .github/workflows/labels.yml
Labels: doc not required, ui not required

#41 features: update tooltips
  src/features/ConfigDataPreview/ConfigDataPreview.tsx
  src/features/Configuration/Configuration.tsx
  src/features/VCOMConfiguration/VCOMConfiguration.tsx
Labels: doc required

#45 Update types on default pins in board definition files
  src/common/boards/BoardControllerConfigDefinition.ts
  src/common/boards/nrf_PCA10153_0.10.0_9161.json
  src/common/boards/nrf_PCA10153_0.9.1_9161.json
  src/common/boards/nrf_PCA10156_0.2.0.json
  src/common/boards/nrf_PCA10156_0.3.0.json
  src/features/Configuration/Configuration.tsx
Labels: doc not required, ui not required

#38 NCD-713: Changelog should not have a title
  Changelog.md
Labels: doc not required, ui not required

#46 Bump version to release v0.1.5. Add changelog entry.
  Changelog.md
  package.json
Labels: doc not required, ui not required

#47 NCD-745: Update 9161 definition
  src/common/boards/nrf_PCA10153_0.10.0_9161.json
Labels: doc not required, ui not required

#48 doc: update supported devices list
  doc/docs/index.md
  doc/docs/revision_history.md
Labels: documentation, doc required

#50 Prepare for release of v0.1.6
  Changelog.md
  package-lock.json
  package.json
Labels: doc not required, ui not required

#52 docs: lower engine version
  Changelog.md
  package.json
Labels: doc required, ui not required

#53 docs: update changelog text
  Changelog.md
Labels: doc not required, ui not required

#54 docs: up version
  package.json
Labels: doc not required, ui not required

#58 NCD-747: Refactor definition loading, add "Reset to default" button
  src/SidePanel.tsx
  src/app/DeviceSelector.tsx
  src/features/Configuration/Configuration.tsx
  src/features/Configuration/boardControllerConfigSlice.ts
  src/features/Configuration/boardDefinitions.ts
Labels: doc required, ui not required

#57 Docs/update engine version
  Changelog.md
  package.json
Labels: doc not required, ui not required

#59 Prepare for release of v0.1.8
  Changelog.md
Labels: doc not required, ui not required
